### ISSUE TITLE
Upgrade media service sdk to 0.9.8 and authenticate with AAD

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/azure-spring-boot#422]
Azure Media Services announces support for AAD and deprecation of ACS authentication

https://azure.microsoft.com/en-us/blog/azure-media-service-aad-auth-and-acs-deprecation/

```
Caused by: com.microsoft.windowsazure.exception.ServiceException: com.sun.jersey.api.client.UniformInterfaceException: POST https://media.windows.net/API/Assets returned a response status of 401 Unauthorized
Response Body: ACS authentication is deprecated. Use AAD authentication : https://docs.microsoft.com/en-us/azure/media-services/media-services-use-aad-auth-to-access-ams-api
	at com.microsoft.windowsazure.services.media.implementation.MediaExceptionProcessor.create(MediaExceptionProcessor.java:142) ~[azure-media-0.9.7.jar:na]
	at sample.mediaservices.MediaServicesSampleApplication.uploadFileAndCreateAsset(MediaServicesSampleApplication.java:54) [classes/:na]
	at sample.mediaservices.MediaServicesSampleApplication.run(MediaServicesSampleApplication.java:40) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	... 5 common frames omitted
```

https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-use-aad-auth-to-access-ams-api

**TODO**
- [x] Upgrade SDK version

- [x] Update authentication to AAD

- [x] Update starter README to add configuration steps

- [x] Update sample with AAD authentication and README
